version: '3'
services:
  api:
    container_name: Fastapi
    restart: always
    build: .
    ports:
      - 8000:8000
    links:
      - mongo
    volumes:
      - .:/usr/src/app

  mongo:
    container_name: mongodatabsae
    image: mongo
    ports:
      - 27017:27017      
